---
# defaults file for rhel10_e8
var_system_crypto_policy: DEFAULT
sysctl_kernel_kptr_restrict_value: '1'
var_selinux_policy_name: targeted
var_selinux_state: enforcing
var_accounts_passwords_pam_faillock_dir: /var/log/faillock
var_auditd_flush: incremental_async
var_auditd_freq: '50'
var_auditd_name_format: hostname
